apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: development
spec:
  generators:
  - list:
      elements:
      - cluster: development
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'dev-applications'
    spec:
      project: 'argo-learnings'
      destination:
        namespace: 'argocd'
        server: https://kubernetes.default.svc
      source:
        path: applications
        repoURL: https://github.com/cbagade/argocd-all
        targetRevision: be9c4752d3ee5a9529e0146d7c4ec2cf864353d9
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 3
          backoff:
            duration: 2m
            factor: 3
            maxDuration: 8m