apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: development
spec:
  generators:
  - list:
      elements:
      - appName: dev-applications
        namespace: argocd
  template:
    metadata:
      name: "{{appName}}"
    spec:
      project: 'argo-learnings'
      destination:
        namespace: "{{namespace}}"
        server: https://kubernetes.default.svc
      source:
        path: applications
        repoURL: https://github.com/cbagade/argocd-all
        targetRevision: e4cd206182cd927e0f4ef7e9a9b94121ac9dc794
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 3
          backoff:
            duration: 2m
            factor: 3
            maxDuration: 8m